// default package
// Generated 22/09/2016 16:11:25 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MeioComunicacao generated by hbm2java
 */
@Entity
@Table(name = "meio_comunicacao", catalog = "accenture_aula")
public class MeioComunicacao implements java.io.Serializable {

	private Integer id;
	private String descricao;

	public MeioComunicacao() {
	}

	public MeioComunicacao(String descricao) {
		this.descricao = descricao;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "descricao", nullable = false, length = 100)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

}
